name: LS Command

on:
  push:
    branches:
      - main
  schedule:
    - cron: '*/5 * * * *'

jobs:
  ls-command:
    runs-on: ubuntu-latest
    
    steps:
    - name: Execute ls command
      run: ls -la
