name: Python Program CI/CD

on:
  workflow_dispatch

jobs:
  run_python_script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2

      - name: Install deps
        run: python -m pip install -r requirements.txt

      - name: Run main.py
        run: python main.py

      - name: Print directory content
        run: ls -la

  print_dir_content:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Print directory content
        run: ls -la
