name: Python CI/CD

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9"]
    
    steps:
    - uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Build and test
      run: |
        pytest tests/
        
    - name: Build Docker image
      run: |
        docker build -t python-app:${{ matrix.python-version }} .
        
    - name: Push Docker image to GitHub Container Registry
      uses: docker:push
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        repository: ${GITHUB_REPOSITORY}/python-app:${{ matrix.python-version }}
