name: Print dir content using tree command

on: 
  workflow_dispatch:
    inputs:
      depthLevel:
        description: 'Depth Level'     
        required: true
        default: '0'
jobs:
  run_python_script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Print directory content
        run: tree -L ${{ github.event.inputs.depthLevel }}
